services:
  postgres:
    image: 'postgres:latest'
    env_file:
      - .env
    ports:
      - '5432'
    networks:
      - botscrew
    volumes:
      - postgres_data:/var/lib.postgresql/data
  botscrew-task:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    networks:
      - botscrew
networks:
  botscrew:
    driver: bridge
volumes:
  postgres_data: