spring:
  application:
    name: BotsCrew-task
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      username: ${SPRING_DATASOURCE_HIKARI_USERNAME}
      password: ${SPRING_DATASOURCE_HIKARI_PASSWORD}
    url: ${SPRING_DATASOURCE_URL}
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: update