spring:
  application:
    name: BotsCrew-task
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    hikari:
      username: sa
      password:
  flyway:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: update
